export const enum ScreenName {
  Splash = 'Splash',
  Home = 'Home',
  Map = 'Map',
  Doctor = 'Doctor',
  Profile = 'Profile',
  Messages = 'Messages',
  Contacts = 'Contacts',
  History = 'History',
  Settings = 'Settings',
  HospitalList = 'HospitalList',
  DiseaseList = 'DiseaseList',
  SettingsButton = 'SettingsButton',
  Language = 'Language',
  DiseaseDetail = 'DiseaseDetail',
  DiseasePropertyDetail = 'DiseasePropertyDetail',
}
